/*
 * JFrame inicial da aplicação
 */

package com.sisgaming.Application;

import com.sisgaming.Tools.Misc;
import com.sisgaming.Tools.Mutex;
import com.sisgaming.Tools.Report;
import javax.swing.JOptionPane;

/**
 * SisGaming / Application / Home
 * @author MrX
 */

public class FrmHome extends javax.swing.JFrame {

    /**
     * Creates new form FrmHome
     */
    public FrmHome() {
        initComponents();
        this.setIconImage(Misc.createIcon().getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        menMenu = new javax.swing.JMenuBar();
        menCad = new javax.swing.JMenu();
        menPesq = new javax.swing.JMenu();
        menRel = new javax.swing.JMenu();
        sepUm = new javax.swing.JPopupMenu.Separator();
        menTd = new javax.swing.JMenuItem();
        sepDois = new javax.swing.JPopupMenu.Separator();
        menSob = new javax.swing.JMenu();
        menDoc = new javax.swing.JMenu();
        menSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SisGaming v 1.0.0");
        setResizable(false);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        menCad.setForeground(new java.awt.Color(0, 0, 204));
        menCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sisgaming/icons/joystick_add.png"))); // NOI18N
        menCad.setText("Cadastrar");
        menCad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menCad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menCadMouseClicked(evt);
            }
        });
        menMenu.add(menCad);

        menPesq.setForeground(new java.awt.Color(0, 0, 204));
        menPesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sisgaming/icons/joystick.png"))); // NOI18N
        menPesq.setText("Pesquisar");
        menPesq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menPesq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menPesqMouseClicked(evt);
            }
        });
        menMenu.add(menPesq);

        menRel.setForeground(new java.awt.Color(0, 0, 204));
        menRel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sisgaming/icons/report.png"))); // NOI18N
        menRel.setText("Relatórios");
        menRel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menRel.add(sepUm);

        menTd.setForeground(new java.awt.Color(0, 0, 204));
        menTd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sisgaming/icons/arrow_in.png"))); // NOI18N
        menTd.setText("Todos");
        menTd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menTd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menTdActionPerformed(evt);
            }
        });
        menRel.add(menTd);
        menRel.add(sepDois);

        menMenu.add(menRel);

        menSob.setForeground(new java.awt.Color(0, 0, 204));
        menSob.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sisgaming/icons/information.png"))); // NOI18N
        menSob.setText("Sobre");
        menSob.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menSob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menSobMouseClicked(evt);
            }
        });
        menMenu.add(menSob);

        menDoc.setForeground(new java.awt.Color(0, 0, 204));
        menDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sisgaming/icons/help.png"))); // NOI18N
        menDoc.setText("Documentação");
        menDoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menDocMouseClicked(evt);
            }
        });
        menMenu.add(menDoc);

        menSair.setForeground(new java.awt.Color(0, 0, 204));
        menSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sisgaming/icons/door_out.png"))); // NOI18N
        menSair.setText("Sair");
        menSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menSairMouseClicked(evt);
            }
        });
        menMenu.add(menSair);

        setJMenuBar(menMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menCadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menCadMouseClicked
        Window.getCadWindow(desktop);
    }//GEN-LAST:event_menCadMouseClicked

    private void menPesqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menPesqMouseClicked
       Window.getUpWindow(desktop);
    }//GEN-LAST:event_menPesqMouseClicked

    private void menTdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menTdActionPerformed
        Report r = new Report();
        r.gamesReport();
    }//GEN-LAST:event_menTdActionPerformed

    private void menSobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menSobMouseClicked
        Window.getSobreWindow();
    }//GEN-LAST:event_menSobMouseClicked

    private void menDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menDocMouseClicked
        Misc.abriDocumentacao();
    }//GEN-LAST:event_menDocMouseClicked

    private void menSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menSairMouseClicked
        int exit = JOptionPane.showConfirmDialog(null, "Deseja sair da aplicação?",
                "Sair?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(exit == 0)
            System.exit(0);
    }//GEN-LAST:event_menSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Mutex.setMutex("Não é possivel executar outra instância da aplicação.", "Erro de inicialização");
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu menCad;
    private javax.swing.JMenu menDoc;
    private javax.swing.JMenuBar menMenu;
    private javax.swing.JMenu menPesq;
    private javax.swing.JMenu menRel;
    private javax.swing.JMenu menSair;
    private javax.swing.JMenu menSob;
    private javax.swing.JMenuItem menTd;
    private javax.swing.JPopupMenu.Separator sepDois;
    private javax.swing.JPopupMenu.Separator sepUm;
    // End of variables declaration//GEN-END:variables
}
